### ISSUE TITLE
Indexing / concordancing

### ISSUE THREAD

**Issue by mikekestemont** [mikekestemont/echoes#2]
- the concordancer often yields empty snippets; we should filter these out.
- I added the `prepare_elmo.py` script which shows how we could we could add sentence-level representations. @fbkarsdorp any chance we can add these vectors to the whoosh index? We could also rely on faiss to get the sentence id, but retrieve it from the whoosh "sentence shop" (instead of the naive sqlite)?

**Comment by fbkarsdorp** [comment]
Re: 1 Switched to elasticsearch, so snippets should be more robust.
Re: 2. Need to think about this some more.

**Comment by fbkarsdorp** [comment]
I think this is done now.
